import type { actions, keypress } from "./hotkeys";

export const DEFAULT_HOTKEYS: Record<keyof actions, keypress> = {
	run: {
		key: "r",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	eat: {
		key: "f",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	lightFire: {
		key: "4",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	equip1: {
		key: "1",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	equip2: {
		key: "2",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	equip3: {
		key: "3",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	badge1: {
		key: "a",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	badge2: {
		key: "s",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	badge3: {
		key: "d",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	badge4: {
		key: "v",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	teleport_everbrook: {
		key: "e",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	remote_sell: {
		key: "s",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	dig: {
		key: "l",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	teleport_mysticvale: {
		key: "m",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	timers: {
		key: "0",
		altKey: false,
		ctrlKey: false,
		metaKey: false,
		shiftKey: false,
	},
	teleport_omboko: {
		key: "o",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	teleport_dock_haven: {
		key: "d",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	auto_hell_burying: {
		key: "b",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	teleport_jafa_outpost: {
		key: "j",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	teleport_frostvale: {
		key: "f",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	hunting_contact: {
		key: "h",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
	mass_pickup: {
		key: "p",
		altKey: false,
		ctrlKey: true,
		metaKey: false,
		shiftKey: false,
	},
};
